[package]
name = "poseidon_merkle"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "PoseidonMerkle â€” zk-Friendly Merkle Trees for NEXi Lattice (Commitments, Proofs, Orchard)"

[dependencies]
nexi = { path = "../" }
poseidon_hash = { path = "../poseidon_hash" }
halo2_gadgets = { git = "https://github.com/zcash/halo2.git", branch = "v2023_07_18" }
pasta_curves = "0.5"
